version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build:
          context: ./
          dockerfile: Dockerfile-multinode
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - FERNET_KEY=MOeAwvkrcPE6nG62ZBhUJOrQsNOe0ON2dzS1nL-4HFo=
        volumes:
            - ./mnt/dags:/usr/local/airflow/dags
            - ./mnt/airflow-multinode.cfg:/usr/local/airflow/airflow.cfg
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
          context: ./
          dockerfile: Dockerfile-multinode
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
          context: ./
          dockerfile: Dockerfile-multinode
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./mnt/dags:/usr/local/airflow/dags
            - ./mnt/airflow-multinode.cfg:/usr/local/airflow/airflow.cfg            
        environment:
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - FERNET_KEY=MOeAwvkrcPE6nG62ZBhUJOrQsNOe0ON2dzS1nL-4HFo=
        command: scheduler

    worker:
        build:
          context: ./
          dockerfile: Dockerfile-multinode
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./mnt/dags:/usr/local/airflow/dags
            - ./mnt/airflow-multinode.cfg:/usr/local/airflow/airflow.cfg
        environment:
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - FERNET_KEY=MOeAwvkrcPE6nG62ZBhUJOrQsNOe0ON2dzS1nL-4HFo=
        command: worker -q weather_queue